# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
