# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160426_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_lunch',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_spicy',
            field=models.BooleanField(default=0),
        ),
    ]
