# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160428_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_spicy',
        ),
        migrations.AddField(
            model_name='menu',
            name='how_spicy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FilePathField(path='/static/img/menu'),
        ),
    ]
