# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160428_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FilePathField(default='', path='/home/timebigot/Projects/akasaka/static/img/menu'),
        ),
    ]
