# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160428_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
