# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160428_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
