# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
