# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160501_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
