# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
